### ISSUE TITLE
plz sir check the code again

### ISSUE THREAD

**Issue by daarkwulf** [facefusion/facefusion#121]
sir with due respect from heart check the code u updated recently
despite tried multiple ways to install this from vscode or conda or etc
still i have to install many stuff while running run.py
like onnxruntime,, insightface,tensorflow
because it always give error code like for eg tensorflow not in module like this

and at last i got the final error like this below
every time i tried diff way to install

Using TensorFlow backend
Traceback (most recent call last):
File "f:\roop\facefusion\facefusion\run.py", line 6, in
core.run()
File "f:\roop\facefusion\facefusion\facefusion\core.py", line 211, in run
parse_args()
File "f:\roop\facefusion\facefusion\facefusion\core.py", line 35, in parse_args
program.add_argument('--frame-processors', help = wording.get('frame_processors_help').format(choices = ', '.join(list_module_names('facefusion/processors/frame/modules'))), dest = 'frame_processors', default = ['face_swapper'], nargs = '+')
TypeError: can only join an iterable

**Comment by daarkwulf** [comment]
it worked somehow.. if someone still getting this issue contact me

**Comment by Tam66662** [comment]
I found that I was getting this error due to an issue with parsing the command line parameters that I specified, specifically when I tried to use `--execution-provider cuda`. As of tag `1.3.1`, It turns out this provider option is not automatically installed as an option in the venv, even though the `--help` indicates it. After running `python install.py --torch cuda --onnxruntime cuda`, this red herring error went away for me, and I was able to run the exact command line that I wanted.
