### ISSUE TITLE
Too much enhancement

### ISSUE THREAD

**Issue by Orchoidizer** [facefusion/facefusion#45]
Any way of 'lessening' the amount of enhancement. It's just TOO good, too sharp unless it's on a 4k target source.
I mean a slider arrangement would be just brilliant of course, but failing that is there anywhere in the code it could be edited?

**Comment by husqvarnas** [comment]
> Any way of 'lessening' the amount of enhancement. It's just TOO good, too sharp unless it's on a 4k target source.
> 
> I mean a slider arrangement would be just brilliant of course, but failing that is there anywhere in the code it could be edited?

**Comment by husqvarnas** [comment]
> Any way of 'lessening' the amount of enhancement. It's just TOO good, too sharp unless it's on a 4k target source.
> 
> I mean a slider arrangement would be just brilliant of course, but failing that is there anywhere in the code it could be edited?

Who are you? And why have you set up an account under my email I'm guessing. I don't exactly know how or what all this stuff means but it's definitely way over my head I'm just wondering who you are because not only am I getting your notifications but the name husqvarnas is closely related to a favorite brand of chainsaw that I like. It may sound silly but I'm just as confused as you might be. I'm not even sure if you'll see this message because I just found the first place this site would let me type in. Lol

**Comment by henryruhs** [comment]
Nope, there is no option for this until frame processors get their dynamic options. Keep an eye on the development, it might come soon.

**Comment by MaansenV** [comment]
im confused now

Am So., 27. Aug. 2023 um 06:07 Uhr schrieb husqvarnas <
***@***.***>:
