### ISSUE TITLE
🚩⚠️💣 security issue - inswapper_128.onnx binary checksum mismatch of original file?

### ISSUE THREAD

**Issue by chrisbward** [facefusion/facefusion#493]
Hi Henry,

Noticed the the binary has been updated - although there is no mention of the checksum of the new file(s), as referenced here;
https://github.com/deepinsight/insightface/issues/2315

You mention the change in binaries here (without checksums);
https://twitter.com/henryruhs/status/1776613658883162369

This leaves the project open to a supply-chain attack, or unofficial implementations floating around, endangering others. 

It's not a great idea publishing such black-boxed binaries, given that the project originated from Roop, the original author a well-known try-hard lame (self-proclaimed grey/blackhat hacker). In infosec circles many of us consider him a clown and a joke.

It was untenable for him to position as a legit security practitioner when distributing binaries in such an unsafe manner - and I'm fairly certain he abandoned the project as he couldn't figure out how to merge pull requests.

Echos of the recent xz utils debacle.

Are you able to provide details of what was changed in order to reproduce the new binaries, or has the project been compromised... thanks.

As an aside he last three commits to the assets/binaries repo are no longer cryptographically signed, and sporadic signing for this repo (different machines?)
https://github.com/facefusion/facefusion-assets/commits/master/

Remedy; 
- provide checksums for all binaries to verify against sources
- provide details on what has changed in the binaries for the checksum mismatch to have occurred
- allow user to apply the changes to their own copy of the original inswapper_128.onnx

**Comment by henryruhs** [comment]
Hey Chris,

before you bad-mouth about Roop and his author, I suggest you take a look into Roop's contributors list.

Not sure why you call a `ONNX` file a binary - it is not an executable. From my knowledge the `ONNX` format is relative safe as the `PROTOBUF` serializer would just not process files that have being modified by malicious code. That makes an attack quite difficult as the attacker has to work around the serializer in the first place - otherwise you get a `Protobuf parsing failed` error.

The team behind InsightFace cannot provide a checksum as it seems they released different versions of the inswapper 128 model. Since then, many people have been involved - it is safe to say there is no official version.

- Hillobar - created the fp16 version
- FaceFusion - removed a model Node that cannot be processed by onnxruntime 1.17.x

**Comment by henryruhs** [comment]
Full disclosure about the changes to the `ONNX` files - it just contains the removal of some casting nodes due the fact that onnxruntime 1.17.x no longer supports it

Link: https://github.com/microsoft/onnxruntime/issues/19437

## Code

```python
#!/usr/bin/env python3

import numpy
import onnx
from onnx import numpy_helper
from onnxruntime.transformers.onnx_model import OnnxModel

model = onnx.load('inswapper_128_fp16.onnx')

onnx_model = OnnxModel(model)
onnx_model.remove_cascaded_cast_nodes()

onnx_initializer = model.graph.initializer[-1]

initializer_array = numpy.array(numpy_helper.to_array(onnx_initializer))
model.graph.initializer.append(numpy_helper.from_array(initializer_array, name = 'initializer'))

onnx.save(model, 'inswapper_128_fp16_v2.onnx')
```

**Comment by henryruhs** [comment]
## Final words

**Comment by henryruhs** [comment]
For me this issue is resolved, next time contact the maintainer of a project before you scare the shit out of people.

**Comment by henryruhs** [comment]
Honestly...

observing you spreading a misleading alert across various [subreddits](https://www.reddit.com/user/Massive_Yogurt6055/) prompts me to remove your access from our GitHub organization. You've already caused significant harm to our reputation and I don't look forward to any of your contribution.
