### ISSUE TITLE
Facefusion video output quality

### ISSUE THREAD

**Issue by iiallgaii** [facefusion/facefusion#80]
The output quality of the video is much lower than the original video, even though it has been adjusted to 100. I hope that the quality can be improved to be closer to the original video. Thank you.

**Comment by henryruhs** [comment]
Thanks for the explanation, the whole mess is caused by Gradio.

1. Upload via gradio.File
1. Upload via gradio.Image
1. FaceFusion processing
1. Upload via Gradio.Image

The first step should not happen or can be prevented once https://github.com/gradio-app/gradio/issues/5809 is solved.

The last step can potentially break the encoding as Gradio tries to convert it again.

That being said, I should print the output file and not the Gradio file to the terminal.

I reopen this issue.

**Comment by light-and-ray** [comment]
If you about master branch - the problem is still here. I've updated, and it still re-encodes target and output videos if codec is not h264

**Comment by henryruhs** [comment]
Problem is on your PC... lols
